### ISSUE TITLE
Support VS2013 and Win8 projects.

### ISSUE THREAD

**Issue by lessneek** [GeertvanHorrik/Caitlyn#1]

**Comment by GeertvanHorrik** [comment]
We now support Win8 and PLC projects.

**Comment by GeertvanHorrik** [comment]
Released a new version via the visual studio gallery.

**Comment by lessneek** [comment]
There is no Caitlyn in VS2013 extensions list.
There is no VS2013 in "supports" here: http://visualstudiogallery.msdn.microsoft.com/079b3fca-e2b1-4fbc-8992-6b3f4134fea9

**Comment by GeertvanHorrik** [comment]
Try again please

**Comment by lessneek** [comment]
It works now. Thank you.
